server:
    port: 9000

spring:
    application:
        name: appservice
    cloud:
        config:
        uri: http://localhost:8761/
        label: master


eureka:
    instance:
        hostname: localhost
        prefer-ip-address: true
        instance-id: ${eureka.instance.hostname}:${server.port}
        nonSecurePort: 80
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka



logging:
    level:
        org:
            springframework:
                security: DEBUG

spring.cloud.vault:
config.lifecycle.enabled: true
fail-fast: true



#ribbon:
#  restclient:
#      enabled: true
#
#feign:
#  hystrix:
#    enabled: true
