server:
  port: 8883
  servlet:
    context-path: /

spring:
  application:
    name: appclient
  cloud:
    config:
      uri: http://localhost:8761/
      label: master


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    instance-id: ${eureka.instance.hostname}:${server.port}
    nonSecurePort: ${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


logging:
  level:
    org:
      springframework:
        security: DEBUG


spring.cloud.vault:
    config.lifecycle.enabled: true
    fail-fast: true